### ISSUE TITLE
Quota filters not set in the proxy-server.conf file of the openio/sds 20.04 image

### ISSUE THREAD

**Issue by BertrandFritsch** [open-io/dockerfiles#123]
Since the release of the openio/sds 20.04 docker image, the container fails to start with following output:

```
LookupError: No section 'container-quotas' (prefixed by 'filter') found in config /etc/oio/sds/OPENIO/oioswift-0/proxy-server.conf
```

Compared to the previous version, `container-quotas` and `account-quotas` filters are no longer in the original proxy-server.conf file, whereas the initialization file of the docker container continues to add them to the keystone pipeline: https://github.com/open-io/dockerfiles/blob/bcde91c5e88c5c3b229fd1bfc97e34837058fd00/openio-sds/20.04/openio-docker-init.sh#L203

**Comment by cdelgehier** [comment]
Merci

**Comment by cdelgehier** [comment]
Can you  `docker pull openio/sds:20.04` and retry please ?

**Comment by BertrandFritsch** [comment]
It works fine. Thank you.
